name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "challenge-chapter-8-ariawan" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          dontuseforce: true
          procfile: "web: npm start"
          env_file: ".env"
        env:
          JWT_SIGNATURE_KEY: ${{secrets.JWT_SIGNATURE_KEY}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_NAME: ${{secrets.DB_NAME}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_PORT: "5432"


          